"""Generate portable S2A artifacts from the Pydantic source models."""

from __future__ import annotations

import json
from pathlib import Path

from models import CONTRACT_MODELS

ROOT = Path(__file__).resolve().parent
SCHEMAS = ROOT / "schemas"


def json_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        parts = [json_type(item) for item in schema["anyOf"]]
        return " | ".join(dict.fromkeys(parts))
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    kind = schema.get("type")
    if kind == "object":
        values = schema.get("additionalProperties")
        value_type = json_type(values) if isinstance(values, dict) else "unknown"
        return f"Record<string, {value_type}>"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown") if kind != "array" else f"{json_type(schema['items'])}[]"


def render_interfaces(schemas: dict[str, dict]) -> str:
    lines = [
        "// Generated by contracts/s2a/generate.py. Do not edit by hand.",
        "",
    ]
    definitions: dict[str, dict] = {}
    for schema in schemas.values():
        definitions.update(schema.get("$defs", {}))
    for name, definition in sorted(definitions.items()):
        if "enum" in definition:
            values = " | ".join(json.dumps(value) for value in definition["enum"])
            lines.extend([f"export type {name} = {values}", ""])
    for schema in schemas.values():
        required = set(schema.get("required", []))
        lines.append(f"export interface {schema['title']} {{")
        for field, field_schema in schema.get("properties", {}).items():
            optional = "" if field in required else "?"
            lines.append(f"  {field}{optional}: {json_type(field_schema)}")
        lines.extend(["}", ""])
    return "\n".join(lines)


def build_artifacts() -> tuple[dict[str, str], str, str]:
    """Return generated files without writing so drift tests need no temp tree."""
    schemas: dict[str, dict] = {}
    for name, model in CONTRACT_MODELS.items():
        schema = model.model_json_schema(mode="validation")
        schema["$id"] = f"https://schemas.atlas.local/s2a/{name}.v1.schema.json"
        schemas[name] = schema
    openapi = {
        "openapi": "3.1.0",
        "info": {"title": "Atlas S2A Common Contracts", "version": "1.0.0"},
        "paths": {},
        "components": {"schemas": schemas},
    }
    schema_files = {
        f"{name}.v1.schema.json": json.dumps(schema, indent=2) + "\n"
        for name, schema in schemas.items()
    }
    return schema_files, json.dumps(openapi, indent=2) + "\n", render_interfaces(schemas)


def main() -> None:
    SCHEMAS.mkdir(parents=True, exist_ok=True)
    schema_files, openapi, typescript = build_artifacts()
    for filename, content in schema_files.items():
        (SCHEMAS / filename).write_text(content, encoding="utf-8")
    (ROOT / "openapi.json").write_text(openapi, encoding="utf-8")
    (ROOT / "types.ts").write_text(typescript, encoding="utf-8")


if __name__ == "__main__":
    main()
