// Generated by contracts/s2a/generate.py. Do not edit by hand.

export type AuditOutcome = "succeeded" | "denied" | "failed"

export type AuthMethod = "password" | "google"

export type ErrorCode = "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "INVALID_INPUT" | "RATE_LIMITED" | "DEPENDENCY_FAILED" | "INTERNAL_ERROR"

export type JobStatus = "queued" | "running" | "succeeded" | "failed" | "cancelled" | "review_required"

export type ModelCallStatus = "reserved" | "running" | "succeeded" | "failed" | "rejected"

export type StepStatus = "pending" | "running" | "succeeded" | "failed" | "skipped"

export interface Principal {
  schema_version: "principal.v1"
  principal_id: string
  tenant_id: string
  auth_method: AuthMethod
  authenticated_at: string
}

export interface AuthReturnTarget {
  schema_version: "auth_return_target.v1"
  origin: string
  return_path?: string
}

export interface CommandEnvelope {
  schema_version: "command.v1"
  command_id: string
  command_type: string
  principal_id: string
  tenant_id: string
  idempotency_key: string
  payload_schema_version: string
  payload: Record<string, unknown>
  requested_at: string
}

export interface ErrorEnvelope {
  schema_version: "error.v1"
  request_id: string
  code: ErrorCode
  message: string
  http_status: number
  retryable?: boolean
  details?: Record<string, unknown>
}

export interface WorkflowJob {
  schema_version: "workflow_job.v1"
  job_id: string
  tenant_id: string
  command_id: string
  workflow_name: string
  workflow_version: string
  status: JobStatus
  attempt_count?: number
  max_attempts?: number
  created_at: string
  updated_at: string
  lease_expires_at?: string | null
  completed_at?: string | null
}

export interface WorkflowStep {
  schema_version: "workflow_step.v1"
  step_id: string
  job_id: string
  tenant_id: string
  step_key: string
  step_name: string
  status: StepStatus
  attempt_count?: number
  started_at?: string | null
  completed_at?: string | null
  error_code?: ErrorCode | null
}

export interface ModelCallRecord {
  schema_version: "model_call.v1"
  model_call_id: string
  tenant_id: string
  job_id: string
  step_id: string
  route: string
  provider: string
  model: string
  prompt_version: string
  output_schema_version: string
  status: ModelCallStatus
  input_tokens?: number
  output_tokens?: number
  cost_usd_micros?: number
  started_at: string
  completed_at?: string | null
}

export interface OutboxEvent {
  schema_version: "outbox_event.v1"
  event_id: string
  event_schema_version: string
  tenant_id: string
  aggregate_type: string
  aggregate_id: string
  event_type: string
  payload: Record<string, unknown>
  occurred_at: string
  available_at: string
  published_at?: string | null
}

export interface AuditEvent {
  schema_version: "audit_event.v1"
  audit_event_id: string
  request_id: string
  tenant_id: string
  principal_id: string
  auth_method: AuthMethod
  action: string
  target_type: string
  target_id?: string | null
  outcome: AuditOutcome
  reason_code?: string | null
  occurred_at: string
  metadata?: Record<string, unknown>
}
